# Site settings
title: 'MAYDAY PAC'
email: info@mayday.us
description: 'MAYDAY PAC'
url: "https://mayday.us" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
development_services_url: //services.mayday.us
# development_services_url: //localhost:3000
blog_root_url: http://blog.mayday.us
blog_feed_url: //services.mayday.us/blog_posts
pledge_url: '//pledge.mayday.us'
github_username:  MayOneUS
twitter_username: MAYDAYUS

# Build settings
markdown: kramdown

assets:
  digest: false

gems:
- jekyll-assets
